--こだわり条件
INSERT INTO UM_COMMON (JOUHOU_SB_CD, KOUMOKU_SB_CD, JOUHOU_SB_NAME, KOUMOKU_SB_NAME, KOUMOKU_SB_RYAKU_NAME, DISP_SORT, KOUMOKU_SB_VAL, BIKOU, APP_DATE, APP_TANTOU_CD, UPD_DATE, UPD_TANTOU_CD, LOGICAL_DEL_FLG, LOGICAL_DEL_DATE, DEL_TANTOU_CD)
VALUES ('006', '3', '予約種別', 'オンライン仲介', 'オンライン仲介', 3, '', '', SYSDATE, '999999', SYSDATE, '999999', '0', NULL, '');
/

